# Generated by Django 4.2.2 on 2023-07-17 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('collection', models.IntegerField()),
                ('index', models.IntegerField()),
                ('subindex', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('include_day', models.BooleanField(default=True)),
                ('include_month', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PhotoIndex.directory')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('block', models.IntegerField(blank=True, null=True)),
                ('parcel', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoIndex.accessionnumber')),
                ('date_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoIndex.daterange')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PhotoIndex.directory')),
                ('places', models.ManyToManyField(to='PhotoIndex.place')),
            ],
        ),
    ]
