# Generated by Django 4.2.2 on 2023-07-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoIndex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='places',
            field=models.ManyToManyField(blank=True, to='PhotoIndex.place'),
        ),
    ]
